// Here's some feat chains that Handy might find handy.

var handysChains = [
  "Advanced Armor Training",
  "Advanced Weapon Training",
  "Aldori Artistry",
  "Aldori Dueling Disciple",
  "Amateur Gunslinger",
  "Amateur Swashbuckler",
  "Aquadynamic Shot",
  "Arcane Armor Training",
  "Armor Adept",
  "Armor Focus",
  "Armor Material Expertise",
  "Armor Material Expertise -> Armor Material Mastery",
  "Armor Proficiency, Heavy",
  "Armor Proficiency, Medium",
  "Armor Trick",
  "Armored Athlete",
  "Artful Dodge",
  "Ascetic Form",
  "Ascetic Form -> Ascetic Strike",
  "Battle Cry",
  "Beastmaster Ire",
  "Blind-Fight",
  "Blind-Fight -> Blinded Competence",
  "Blind-Fight -> Improved Blind-Fight",
  "Blind-Fight -> Improved Blind-Fight -> Greater Blind-Fight",
  "Blind-Fight -> Moonlight Stalker",
  "Blind-Fight -> Moonlight Stalker -> Moonlight Stalker Feint",
  "Blind-Fight -> Moonlight Stalker -> Moonlight Stalker Feint -> Moonlight Stalker Master",
  "Blind-Fight -> Moonlight Stalker -> Moonlight Stalker Master",
  "Blind-Fight -> Moonlight Stalker Feint",
  "Blind-Fight -> Moonlight Stalker Feint -> Moonlight Stalker Master",
  "Blind-Fight -> Moonlight Stalker Master",
  "Blood Spurt",
  "Bloody Mess",
  "Bullying Blow",
  "But a Scratch",
  "Call Out",
  "Chairbreaker",
  "Combat Expertise",
  "Combat Expertise -> Archon Diversion",
  "Combat Expertise -> Archon Diversion -> Archon Justice",
  "Combat Expertise -> Blinding Flash",
  "Combat Expertise -> Break Guard",
  "Combat Expertise -> Butterfly's Sting",
  "Combat Expertise -> Cloak and Dagger Subterfuge",
  "Combat Expertise -> Cloak and Dagger Subterfuge -> Cloak and Dagger Tactics",
  "Combat Expertise -> Directed Disarm",
  "Combat Expertise -> Dirty Disarm",
  "Combat Expertise -> Dirty Grapple",
  "Combat Expertise -> Disarming Strike",
  "Combat Expertise -> Disengaging Feint",
  "Combat Expertise -> Disengaging Feint -> Disengaging Flourish",
  "Combat Expertise -> Disengaging Feint -> Disengaging Shot",
  "Combat Expertise -> Disengaging Flourish",
  "Combat Expertise -> Disengaging Shot",
  "Combat Expertise -> Diva Strike",
  "Combat Expertise -> Divert Harm",
  "Combat Expertise -> Drag Down",
  "Combat Expertise -> Feinting Flurry",
  "Combat Expertise -> Felling Escape",
  "Combat Expertise -> Felling Smash",
  "Combat Expertise -> Fox Trickery",
  "Combat Expertise -> Gang Up",
  "Combat Expertise -> Gang Up -> Team Up",
  "Combat Expertise -> Greater Dirty Trick",
  "Combat Expertise -> Greater Dirty Trick -> Dirty Trick Master",
  "Combat Expertise -> Greater Reposition",
  "Combat Expertise -> Illusive Gnome Surprise",
  "Combat Expertise -> Improved Dirty Trick",
  "Combat Expertise -> Improved Dirty Trick -> Greater Dirty Trick",
  "Combat Expertise -> Improved Dirty Trick -> Greater Dirty Trick -> Dirty Trick Master",
  "Combat Expertise -> Improved Dirty Trick -> Quick Dirty Trick",
  "Combat Expertise -> Improved Disarm",
  "Combat Expertise -> Improved Disarm -> Break Guard",
  "Combat Expertise -> Improved Disarm -> Dirty Disarm",
  "Combat Expertise -> Improved Disarm -> Disarming Strike",
  "Combat Expertise -> Improved Disarm -> Greater Disarm",
  "Combat Expertise -> Improved Disarm -> Greater Disarm -> Directed Disarm",
  "Combat Expertise -> Improved Disarm -> Hold the Blade",
  "Combat Expertise -> Improved Feint",
  "Combat Expertise -> Improved Feint -> Disengaging Feint",
  "Combat Expertise -> Improved Feint -> Disengaging Feint -> Disengaging Flourish",
  "Combat Expertise -> Improved Feint -> Disengaging Feint -> Disengaging Shot",
  "Combat Expertise -> Improved Feint -> Diva Advance",
  "Combat Expertise -> Improved Feint -> Diva Strike",
  "Combat Expertise -> Improved Feint -> Greater Feint",
  "Combat Expertise -> Improved Feint -> Illusive Gnome Surprise",
  "Combat Expertise -> Improved Feint -> Incite Paranoia",
  "Combat Expertise -> Improved Feint -> Moonlight Stalker Feint",
  "Combat Expertise -> Improved Feint -> Moonlight Stalker Feint -> Moonlight Stalker Master",
  "Combat Expertise -> Improved Feint -> Moonlight Stalker Master",
  "Combat Expertise -> Improved Hammer Throw",
  "Combat Expertise -> Improved Parry",
  "Combat Expertise -> Improved Reposition",
  "Combat Expertise -> Improved Reposition -> Crashing Wave Buffet",
  "Combat Expertise -> Improved Reposition -> Crashing Wave Buffet -> Crashing Wave Fist",
  "Combat Expertise -> Improved Reposition -> Greater Reposition",
  "Combat Expertise -> Improved Reposition -> Pummeling Bully",
  "Combat Expertise -> Improved Reposition -> Quick Reposition",
  "Combat Expertise -> Improved Reposition -> Wings of the Androsphinx",
  "Combat Expertise -> Improved Second Chance",
  "Combat Expertise -> Improved Trip",
  "Combat Expertise -> Improved Trip -> Binding Throw",
  "Combat Expertise -> Improved Trip -> Brute Stomp",
  "Combat Expertise -> Improved Trip -> Brute Stomp -> Brute Assault",
  "Combat Expertise -> Improved Trip -> Drag Down",
  "Combat Expertise -> Improved Trip -> Felling Escape",
  "Combat Expertise -> Improved Trip -> Felling Smash",
  "Combat Expertise -> Improved Trip -> Fury's Fall",
  "Combat Expertise -> Improved Trip -> Greater Trip",
  "Combat Expertise -> Improved Trip -> Improved Hammer Throw",
  "Combat Expertise -> Improved Trip -> Ki Throw",
  "Combat Expertise -> Improved Trip -> Ki Throw -> Binding Throw",
  "Combat Expertise -> Improved Trip -> Ki Throw -> Improved Ki Throw",
  "Combat Expertise -> Improved Trip -> Ki Throw -> Spinning Throw",
  "Combat Expertise -> Improved Trip -> Pummeling Bully",
  "Combat Expertise -> Improved Trip -> Repositioning Strike",
  "Combat Expertise -> Improved Trip -> Spinning Throw",
  "Combat Expertise -> Improved Trip -> Tripping Strike",
  "Combat Expertise -> Improved Trip -> Tripping Twirl",
  "Combat Expertise -> Improved Two-Weapon Feint",
  "Combat Expertise -> Incite Paranoia",
  "Combat Expertise -> Kitsune Tricks",
  "Combat Expertise -> Kitsune Tricks -> Kitsune Vengeance",
  "Combat Expertise -> Kitsune Vengeance",
  "Combat Expertise -> Merciless Beating",
  "Combat Expertise -> Mirror Move",
  "Combat Expertise -> Misdirection Attack",
  "Combat Expertise -> Misdirection Redirection",
  "Combat Expertise -> Misdirection Redirection -> Misdirection Attack",
  "Combat Expertise -> Misdirection Tactics",
  "Combat Expertise -> Misdirection Tactics -> Misdirection Redirection",
  "Combat Expertise -> Misdirection Tactics -> Misdirection Redirection -> Misdirection Attack",
  "Combat Expertise -> Moonlight Stalker",
  "Combat Expertise -> Moonlight Stalker -> Moonlight Stalker Feint",
  "Combat Expertise -> Moonlight Stalker -> Moonlight Stalker Feint -> Moonlight Stalker Master",
  "Combat Expertise -> Moonlight Stalker -> Moonlight Stalker Master",
  "Combat Expertise -> Moonlight Stalker Feint",
  "Combat Expertise -> Moonlight Stalker Feint -> Moonlight Stalker Master",
  "Combat Expertise -> Moonlight Stalker Master",
  "Combat Expertise -> Porcupine Defense",
  "Combat Expertise -> Quick Dirty Trick",
  "Combat Expertise -> Quick Reposition",
  "Combat Expertise -> Repositioning Strike",
  "Combat Expertise -> Second Chance",
  "Combat Expertise -> Second Chance -> Improved Second Chance",
  "Combat Expertise -> Slayer's Feint",
  "Combat Expertise -> Snoutgrip",
  "Combat Expertise -> Spinning Throw",
  "Combat Expertise -> Strike True",
  "Combat Expertise -> Superior Dirty Trick",
  "Combat Expertise -> Tactical Reposition",
  "Combat Expertise -> Team Up",
  "Combat Expertise -> Tripping Strike",
  "Combat Expertise -> Tripping Twirl",
  "Combat Expertise -> Two-Weapon Feint",
  "Combat Expertise -> Two-Weapon Feint -> Improved Two-Weapon Feint",
  "Combat Expertise -> Unblinking Flame Feint",
  "Combat Expertise -> Unblinking Flame Feint -> Unblinking Flame Fist",
  "Combat Expertise -> Unblinking Flame Fist",
  "Combat Expertise -> Whirlwind Attack",
  "Combat Expertise -> Wings of the Androsphinx",
  "Combat Reflexes",
  "Combat Reflexes -> Archon Diversion",
  "Combat Reflexes -> Archon Diversion -> Archon Justice",
  "Combat Reflexes -> Bodyguard",
  "Combat Reflexes -> Bodyguard -> In Harm's Way",
  "Combat Reflexes -> Brute Stomp",
  "Combat Reflexes -> Brute Stomp -> Brute Assault",
  "Combat Reflexes -> Combat Patrol",
  "Combat Reflexes -> Counterpunch",
  "Combat Reflexes -> Deceitful Incompetence",
  "Combat Reflexes -> Diabolic Humiliation",
  "Combat Reflexes -> Diabolic Humiliation -> Diabolic Judgement",
  "Combat Reflexes -> Diabolic Judgement",
  "Combat Reflexes -> Indomitable Mountain Avalanche",
  "Combat Reflexes -> Indomitable Mountain Peak",
  "Combat Reflexes -> Indomitable Mountain Peak -> Indomitable Mountain Avalanche",
  "Combat Reflexes -> Panther Claw",
  "Combat Reflexes -> Panther Claw -> Panther Parry",
  "Combat Reflexes -> Panther Parry",
  "Combat Reflexes -> Pin Down",
  "Combat Reflexes -> Porcupine Defense",
  "Combat Reflexes -> Shrewd Tactician",
  "Combat Reflexes -> Snake Fang",
  "Combat Reflexes -> Snoutgrip",
  "Combat Reflexes -> Stand Still",
  "Combat Reflexes -> Vanguard Hustle",
  "Combat Reflexes -> Vanguard Ward",
  "Combat Reflexes -> Vanguard Ward -> Vanguard Hustle",
  "Combat Reflexes -> Vicious Stomp",
  "Combat Reflexes -> Vicious Stomp -> Brute Stomp",
  "Combat Reflexes -> Vicious Stomp -> Brute Stomp -> Brute Assault",
  "Combat Reflexes -> Vigilant Charger",
  "Combat Stamina",
  "Combat Stamina -> Push the Limits",
  "Combat Vigor",
  "Combat Vigor -> Fortuitous Vigor",
  "Cudgeler Sweep",
  "Cudgeler Sweep -> Cudgeler Takedown",
  "Deadly Aim",
  "Deadly Finish",
  "Death from Above",
  "Death from Below",
  "Deathless Initiate",
  "Deathless Initiate -> Deathless Master",
  "Deathless Initiate -> Deathless Master -> Deathless Zealot",
  "Deathless Initiate -> Deathless Zealot",
  "Dedicated Adversary",
  "Defended Movement",
  "Defensive Combat Training",
  "Defensive Weapon Training",
  "Desperate Battler",
  "Dirty Fighting",
  "Disruptive",
  "Disruptive -> Spellbreaker",
  "Disruptive -> Sunder Blessing",
  "Dodge",
  "Dodge -> Anticipate Dodge",
  "Dodge -> Anticipate Dodge -> Counter Reflexes",
  "Dodge -> Azata Mischief",
  "Dodge -> Azata Mischief -> Azata Sprint",
  "Dodge -> Canny Tumble",
  "Dodge -> Circling Mongoose",
  "Dodge -> Crane Wing",
  "Dodge -> Crane Wing -> Crane Riposte",
  "Dodge -> Disengaging Shot",
  "Dodge -> Greater Spring Attack",
  "Dodge -> Improved Punishing Step",
  "Dodge -> Improved Sidestep",
  "Dodge -> Improved Spring Attack",
  "Dodge -> Improved Spring Attack -> Greater Spring Attack",
  "Dodge -> Jabbing Dancer",
  "Dodge -> Jabbing Dancer -> Jabbing Master",
  "Dodge -> Jabbing Master",
  "Dodge -> Juke",
  "Dodge -> Just Out of Reach",
  "Dodge -> Landing Roll",
  "Dodge -> Mobility",
  "Dodge -> Mobility -> Anticipate Dodge",
  "Dodge -> Mobility -> Anticipate Dodge -> Counter Reflexes",
  "Dodge -> Mobility -> Azata Mischief",
  "Dodge -> Mobility -> Azata Mischief -> Azata Sprint",
  "Dodge -> Mobility -> Canny Tumble",
  "Dodge -> Mobility -> Circling Mongoose",
  "Dodge -> Mobility -> Combat Patrol",
  "Dodge -> Mobility -> Disengaging Shot",
  "Dodge -> Mobility -> Improved Sidestep",
  "Dodge -> Mobility -> Improved Spring Attack",
  "Dodge -> Mobility -> Improved Spring Attack -> Greater Spring Attack",
  "Dodge -> Mobility -> Jabbing Dancer",
  "Dodge -> Mobility -> Jabbing Dancer -> Jabbing Master",
  "Dodge -> Mobility -> Juke",
  "Dodge -> Mobility -> Just Out of Reach",
  "Dodge -> Mobility -> Landing Roll",
  "Dodge -> Mobility -> Parting Shot",
  "Dodge -> Mobility -> Shot on the Run",
  "Dodge -> Mobility -> Shot on the Run -> Parting Shot",
  "Dodge -> Mobility -> Sidestep",
  "Dodge -> Mobility -> Sidestep -> Improved Sidestep",
  "Dodge -> Mobility -> Spring Attack",
  "Dodge -> Mobility -> Spring Attack -> Circling Mongoose",
  "Dodge -> Mobility -> Spring Attack -> Improved Spring Attack",
  "Dodge -> Mobility -> Spring Attack -> Improved Spring Attack -> Greater Spring Attack",
  "Dodge -> Mobility -> Spring Attack -> Whirlwind Attack",
  "Dodge -> Mobility -> Spring-Heeled Reaping",
  "Dodge -> Mobility -> Spring-Heeled Sprint",
  "Dodge -> Mobility -> Spring-Heeled Sprint -> Spring-Heeled Reaping",
  "Dodge -> Mobility -> Stag Horns",
  "Dodge -> Mobility -> Stag Horns -> Stag Submission",
  "Dodge -> Mobility -> Stag Submission",
  "Dodge -> Mobility -> Vanguard Hustle",
  "Dodge -> Osyluth Guile",
  "Dodge -> Parting Shot",
  "Dodge -> Punishing Step",
  "Dodge -> Punishing Step -> Improved Punishing Step",
  "Dodge -> Redirect Attack",
  "Dodge -> Sidestep",
  "Dodge -> Sidestep -> Improved Sidestep",
  "Dodge -> Spring-Heeled Reaping",
  "Dodge -> Spring-Heeled Sprint",
  "Dodge -> Spring-Heeled Sprint -> Spring-Heeled Reaping",
  "Dodge -> Stag Horns",
  "Dodge -> Stag Horns -> Stag Submission",
  "Dodge -> Stag Submission",
  "Dodge -> Sweeping Dodge",
  "Dodge -> Underfoot (BotB)",
  "Dodge -> Wind Stance",
  "Dodge -> Wind Stance -> Azata Sprint",
  "Dodge -> Wind Stance -> Lightning Stance",
  "Dodge -> Woodland Wraith",
  "Eldritch Claws",
  "Elven Battle Torrent",
  "Enforcer",
  "Equipment Trick",
  "Filthy Weapons",
  "Flagbearer",
  "Flanking Foil",
  "Focused Discipline",
  "Following Step",
  "Following Step -> Step Up and Strike",
  "Footslasher",
  "Fortified Armor Training",
  "Fox Insight",
  "Fox Insight -> Fox Trickery",
  "Frightening Ambush",
  "Frightening Ambush -> Terrifying Assault",
  "Ground-Grabber",
  "Grudge Fighter",
  "Hammer the Gap",
  "Haunted Gnome",
  "Hellcat Pounce",
  "Holy Water Assault",
  "Hook Fighter",
  "Horn Rider",
  "Horn Rider -> Horn Rider's Charge",
  "Horn of the Criosphinx",
  "Horrific Gorging",
  "Horse Master",
  "Implacable",
  "Improved Awesome Blow",
  "Improved Beast Hunter",
  "Improved Bravery",
  "Improved Charging Hurler",
  "Improved Critical",
  "Improved Initiative",
  "Improved Initiative -> Befuddling Initiative",
  "Improved Initiative -> Ready for Anything",
  "Improved Initiative -> Surprising Combatant",
  "Improved Intercept Blow",
  "Improved Low Blow",
  "Improved Precise Shot",
  "Improved Rending Fury",
  "Improved Rending Fury -> Greater Rending Fury",
  "Improved Shield Bash",
  "Improved Shield Bash -> Shield Slam",
  "Improved Unarmed Strike",
  "Improved Unarmed Strike -> Adder Strike",
  "Improved Unarmed Strike -> Befuddling Strike",
  "Improved Unarmed Strike -> Belier's Bite",
  "Improved Unarmed Strike -> Blood Frenzy Assault",
  "Improved Unarmed Strike -> Boar Ferocity",
  "Improved Unarmed Strike -> Boar Ferocity -> Boar Shred",
  "Improved Unarmed Strike -> Boar Shred",
  "Improved Unarmed Strike -> Brute Stomp",
  "Improved Unarmed Strike -> Brute Stomp -> Brute Assault",
  "Improved Unarmed Strike -> Cockatrice Strike",
  "Improved Unarmed Strike -> Combat Style Master",
  "Improved Unarmed Strike -> Counterpunch",
  "Improved Unarmed Strike -> Crane Wing",
  "Improved Unarmed Strike -> Crane Wing -> Crane Riposte",
  "Improved Unarmed Strike -> Crashing Wave Buffet",
  "Improved Unarmed Strike -> Crashing Wave Buffet -> Crashing Wave Fist",
  "Improved Unarmed Strike -> Crushing Blow",
  "Improved Unarmed Strike -> Dazing Fist",
  "Improved Unarmed Strike -> Deadhand Master",
  "Improved Unarmed Strike -> Deflect Arrows",
  "Improved Unarmed Strike -> Dolphin Dart",
  "Improved Unarmed Strike -> Dragon Ferocity",
  "Improved Unarmed Strike -> Dragon Roar",
  "Improved Unarmed Strike -> Electric Eel Shock",
  "Improved Unarmed Strike -> Electric Eel Shock -> Electric Eel Conduit",
  "Improved Unarmed Strike -> Elemental Fist",
  "Improved Unarmed Strike -> Elemental Fist -> Djinni Spirit",
  "Improved Unarmed Strike -> Elemental Fist -> Djinni Spirit -> Djinni Spin",
  "Improved Unarmed Strike -> Elemental Fist -> Efreeti Stance",
  "Improved Unarmed Strike -> Elemental Fist -> Efreeti Stance -> Efreeti Touch",
  "Improved Unarmed Strike -> Elemental Fist -> Marid Coldsnap",
  "Improved Unarmed Strike -> Elemental Fist -> Marid Spirit",
  "Improved Unarmed Strike -> Elemental Fist -> Marid Spirit -> Marid Coldsnap",
  "Improved Unarmed Strike -> Elemental Fist -> Shaitan Earthblast",
  "Improved Unarmed Strike -> Elemental Fist -> Shaitan Skin",
  "Improved Unarmed Strike -> Elemental Fist -> Shaitan Skin -> Shaitan Earthblast",
  "Improved Unarmed Strike -> Feral Combat Training",
  "Improved Unarmed Strike -> Hamatulatsu",
  "Improved Unarmed Strike -> Hex Strike",
  "Improved Unarmed Strike -> Hurricane Punch",
  "Improved Unarmed Strike -> Improved Grapple",
  "Improved Unarmed Strike -> Improved Grapple -> Binding Throw",
  "Improved Unarmed Strike -> Improved Grapple -> Body Shield",
  "Improved Unarmed Strike -> Improved Grapple -> Bonebreaker",
  "Improved Unarmed Strike -> Improved Grapple -> Bonebreaker -> Neckbreaker",
  "Improved Unarmed Strike -> Improved Grapple -> Bull-Catcher Toss",
  "Improved Unarmed Strike -> Improved Grapple -> Bull-Catcher Toss -> Bull-Catcher Wrangler",
  "Improved Unarmed Strike -> Improved Grapple -> Bushwhack",
  "Improved Unarmed Strike -> Improved Grapple -> Chokehold",
  "Improved Unarmed Strike -> Improved Grapple -> Claw Wrench",
  "Improved Unarmed Strike -> Improved Grapple -> Deadly Grappler",
  "Improved Unarmed Strike -> Improved Grapple -> Dirty Grapple",
  "Improved Unarmed Strike -> Improved Grapple -> Explosive Escape",
  "Improved Unarmed Strike -> Improved Grapple -> Grabbing Drag",
  "Improved Unarmed Strike -> Improved Grapple -> Grabbing Drag -> Grabbing Master",
  "Improved Unarmed Strike -> Improved Grapple -> Greater Grapple",
  "Improved Unarmed Strike -> Improved Grapple -> Greater Grapple -> Neckbreaker",
  "Improved Unarmed Strike -> Improved Grapple -> Greater Grapple -> Pinning Knockout",
  "Improved Unarmed Strike -> Improved Grapple -> Greater Grapple -> Pinning Rend",
  "Improved Unarmed Strike -> Improved Grapple -> Greater Grapple -> Rapid Grappler",
  "Improved Unarmed Strike -> Improved Grapple -> Greater Grapple -> Sleeper Hold",
  "Improved Unarmed Strike -> Improved Grapple -> Hamatula Strike",
  "Improved Unarmed Strike -> Improved Grapple -> Hamatula Strike -> Hamatula Grasp",
  "Improved Unarmed Strike -> Improved Grapple -> Kraken Throttle",
  "Improved Unarmed Strike -> Improved Grapple -> Kraken Wrack",
  "Improved Unarmed Strike -> Improved Grapple -> Snapping Turtle Clutch",
  "Improved Unarmed Strike -> Improved Grapple -> Snapping Turtle Clutch -> Snapping Turtle Shell",
  "Improved Unarmed Strike -> Improved Grapple -> Snoutgrip",
  "Improved Unarmed Strike -> Improved Grapple -> Stunning Pin",
  "Improved Unarmed Strike -> Improved Grapple -> Tatzlwyrm Grappler",
  "Improved Unarmed Strike -> Improved Grapple -> Tatzlwyrm Grappler -> Tatzlwyrm Rake",
  "Improved Unarmed Strike -> Improved Grapple -> Tatzlwyrm Rake",
  "Improved Unarmed Strike -> Improved Grapple -> Unfair Grip",
  "Improved Unarmed Strike -> Indomitable Mountain Avalanche",
  "Improved Unarmed Strike -> Indomitable Mountain Peak",
  "Improved Unarmed Strike -> Indomitable Mountain Peak -> Indomitable Mountain Avalanche",
  "Improved Unarmed Strike -> Jabbing Dancer",
  "Improved Unarmed Strike -> Jabbing Dancer -> Jabbing Master",
  "Improved Unarmed Strike -> Jabbing Master",
  "Improved Unarmed Strike -> Jawbreaker",
  "Improved Unarmed Strike -> Jawbreaker -> Bonebreaker",
  "Improved Unarmed Strike -> Jawbreaker -> Bonebreaker -> Neckbreaker",
  "Improved Unarmed Strike -> Joyless Toil",
  "Improved Unarmed Strike -> Ki Throw",
  "Improved Unarmed Strike -> Ki Throw -> Binding Throw",
  "Improved Unarmed Strike -> Ki Throw -> Improved Ki Throw",
  "Improved Unarmed Strike -> Ki Throw -> Spinning Throw",
  "Improved Unarmed Strike -> Linnorm Wrath",
  "Improved Unarmed Strike -> Mantis Torment",
  "Improved Unarmed Strike -> Mantis Wisdom",
  "Improved Unarmed Strike -> Mantis Wisdom -> Mantis Torment",
  "Improved Unarmed Strike -> Panther Claw",
  "Improved Unarmed Strike -> Panther Claw -> Panther Parry",
  "Improved Unarmed Strike -> Panther Parry",
  "Improved Unarmed Strike -> Paralyzing Strike",
  "Improved Unarmed Strike -> Perfect Strike",
  "Improved Unarmed Strike -> Psychovore Master",
  "Improved Unarmed Strike -> Psychovore Strike",
  "Improved Unarmed Strike -> Psychovore Strike -> Psychovore Master",
  "Improved Unarmed Strike -> Pummeling Bully",
  "Improved Unarmed Strike -> Pummeling Charge",
  "Improved Unarmed Strike -> Punishing Kick",
  "Improved Unarmed Strike -> Scorpion Style",
  "Improved Unarmed Strike -> Scorpion Style -> Gorgon's Fist",
  "Improved Unarmed Strike -> Scorpion Style -> Gorgon's Fist -> Medusa's Wrath",
  "Improved Unarmed Strike -> Shark Tear",
  "Improved Unarmed Strike -> Snake Fang",
  "Improved Unarmed Strike -> Snake Sidewind",
  "Improved Unarmed Strike -> Snake Sidewind -> Snake Fang",
  "Improved Unarmed Strike -> Spinning Throw",
  "Improved Unarmed Strike -> Stag Horns",
  "Improved Unarmed Strike -> Stag Horns -> Stag Submission",
  "Improved Unarmed Strike -> Stag Submission",
  "Improved Unarmed Strike -> Staggering Fist",
  "Improved Unarmed Strike -> Street Carnage",
  "Improved Unarmed Strike -> Street Sweep",
  "Improved Unarmed Strike -> Street Sweep -> Street Carnage",
  "Improved Unarmed Strike -> Stunning Fist",
  "Improved Unarmed Strike -> Stunning Fist -> Crushing Blow",
  "Improved Unarmed Strike -> Stunning Fist -> Disorienting Blow",
  "Improved Unarmed Strike -> Stunning Fist -> Dragon Ferocity",
  "Improved Unarmed Strike -> Stunning Fist -> Dragon Roar",
  "Improved Unarmed Strike -> Stunning Fist -> Jawbreaker",
  "Improved Unarmed Strike -> Stunning Fist -> Jawbreaker -> Bonebreaker",
  "Improved Unarmed Strike -> Stunning Fist -> Jawbreaker -> Bonebreaker -> Neckbreaker",
  "Improved Unarmed Strike -> Stunning Fist -> Mantis Wisdom",
  "Improved Unarmed Strike -> Stunning Fist -> Mantis Wisdom -> Mantis Torment",
  "Improved Unarmed Strike -> Stunning Fist -> Stone-Handed",
  "Improved Unarmed Strike -> Stunning Fist -> Stunning Fist Adept",
  "Improved Unarmed Strike -> Stunning Fist -> Stunning Pin",
  "Improved Unarmed Strike -> Stunning Fist -> Unblinking Flame Fist",
  "Improved Unarmed Strike -> Tiger Claws",
  "Improved Unarmed Strike -> Tiger Claws -> Tiger Pounce",
  "Improved Unarmed Strike -> Tiger Pounce",
  "Improved Unarmed Strike -> Vicious Stomp",
  "Improved Unarmed Strike -> Vicious Stomp -> Brute Stomp",
  "Improved Unarmed Strike -> Vicious Stomp -> Brute Stomp -> Brute Assault",
  "Improved Unarmed Strike -> Wilding Strike",
  "Improved Whip Mastery",
  "Inspiring Bravery",
  "Intimidating Prowess",
  "Intimidating Prowess -> Orc Rampage",
  "Intimidating Prowess -> Orc Rampage -> Orc Snarl",
  "Intimidating Prowess -> Orc Snarl",
  "Intimidating Prowess -> Shocking Bellow",
  "Intimidating Prowess -> Visceral Threat",
  "Ironclad Reactions",
  "Jaguar Pounce",
  "Lob Shot",
  "Low Profile",
  "Lunge",
  "Lunge -> Monkey Lunge",
  "Lunge -> Outslug Sprint",
  "Lunge -> Outslug Weave",
  "Lunge -> Outslug Weave -> Outslug Sprint",
  "Martial Dominance",
  "Martial Focus",
  "Measure Foe",
  "Modification Trainer",
  "Modified Weapon Proficiency",
  "Multiattack",
  "Mutual Hatred",
  "Obscuring Beacon",
  "Opportunistic Grappler",
  "Orc Weapon Expertise",
  "Patient Strike",
  "Performance Weapon Mastery",
  "Phalanx Formation",
  "Poised Bearing",
  "Position of Strength",
  "Position of Strength -> Improved Position of Strength",
  "Power Attack",
  "Power Attack -> All-Consuming Swing",
  "Power Attack -> Bloody Assault",
  "Power Attack -> Bloody Assault -> Blood Frenzy Assault",
  "Power Attack -> Cleave",
  "Power Attack -> Cleave -> All-Consuming Swing",
  "Power Attack -> Cleave -> Cleaving Finish",
  "Power Attack -> Cleave -> Cleaving Finish -> Improved Cleaving Finish",
  "Power Attack -> Cleave -> Demonic Slaughter",
  "Power Attack -> Cleave -> Great Cleave",
  "Power Attack -> Cleave -> Great Cleave -> Demonic Slaughter",
  "Power Attack -> Cleave -> Great Cleave -> Improved Cleaving Finish",
  "Power Attack -> Cleave -> Great Cleave -> Improved Surprise Follow-Through",
  "Power Attack -> Cleave -> Improved Cleaving Finish",
  "Power Attack -> Cleave -> Improved Surprise Follow-Through",
  "Power Attack -> Cleave -> Surprise Follow-Through",
  "Power Attack -> Cornugon Smash",
  "Power Attack -> Dazing Assault",
  "Power Attack -> Death or Glory",
  "Power Attack -> Destructive Persuasion",
  "Power Attack -> Dreadful Carnage",
  "Power Attack -> Elephant Stomp",
  "Power Attack -> Felling Smash",
  "Power Attack -> Furious Focus",
  "Power Attack -> Furious Focus -> Dreadful Carnage",
  "Power Attack -> Hurtful",
  "Power Attack -> Hurtful -> Pile On",
  "Power Attack -> Improved Bull Rush",
  "Power Attack -> Improved Bull Rush -> Bristling Bull Rush",
  "Power Attack -> Improved Bull Rush -> Bull Rush Strike",
  "Power Attack -> Improved Bull Rush -> Demonic Momentum",
  "Power Attack -> Improved Bull Rush -> Demonic Momentum -> Demonic Slaughter",
  "Power Attack -> Improved Bull Rush -> Greater Bull Rush",
  "Power Attack -> Improved Bull Rush -> Hurricane Punch",
  "Power Attack -> Improved Bull Rush -> Improved Ki Throw",
  "Power Attack -> Improved Bull Rush -> Quick Bull Rush",
  "Power Attack -> Improved Bull Rush -> Rebuffing Reduction",
  "Power Attack -> Improved Bull Rush -> Rhino Charge",
  "Power Attack -> Improved Bull Rush -> Spinning Throw",
  "Power Attack -> Improved Bull Rush -> Street Carnage",
  "Power Attack -> Improved Bull Rush -> Street Sweep",
  "Power Attack -> Improved Bull Rush -> Street Sweep -> Street Carnage",
  "Power Attack -> Improved Bull Rush -> Unseat",
  "Power Attack -> Improved Drag",
  "Power Attack -> Improved Drag -> Bristling Drag",
  "Power Attack -> Improved Drag -> Crashing Wave Buffet",
  "Power Attack -> Improved Drag -> Crashing Wave Buffet -> Crashing Wave Fist",
  "Power Attack -> Improved Drag -> Greater Drag",
  "Power Attack -> Improved Drag -> Quick Drag",
  "Power Attack -> Improved Overrun",
  "Power Attack -> Improved Overrun -> Brute Stomp",
  "Power Attack -> Improved Overrun -> Brute Stomp -> Brute Assault",
  "Power Attack -> Improved Overrun -> Charge Through",
  "Power Attack -> Improved Overrun -> Elephant Stomp",
  "Power Attack -> Improved Overrun -> Greater Overrun",
  "Power Attack -> Improved Sunder",
  "Power Attack -> Improved Sunder -> Gate Breaker",
  "Power Attack -> Improved Sunder -> Gate Breaker -> Relic Breaker",
  "Power Attack -> Improved Sunder -> Greater Sunder",
  "Power Attack -> Improved Sunder -> Shrapnel Strike",
  "Power Attack -> Improved Sunder -> Smashing Crush",
  "Power Attack -> Improved Sunder -> Smashing Crush -> Smashing Dent",
  "Power Attack -> Improved Sunder -> Smashing Dent",
  "Power Attack -> Improved Sunder -> Sundering Strike",
  "Power Attack -> Improved Uncivilized Tactics",
  "Power Attack -> Improved Uncivilized Tactics -> Greater Uncivilized Tactics",
  "Power Attack -> Jabbing Master",
  "Power Attack -> Pushing Assault",
  "Power Attack -> Rhino Charge",
  "Power Attack -> Smiting Reversal",
  "Power Attack -> Staggering Blow",
  "Power Attack -> Stunning Assault",
  "Power Attack -> Stunning Irruption",
  "Power Attack -> Tiger Pounce",
  "Power Attack -> Uncivilized Tactics",
  "Power Attack -> Uncivilized Tactics -> Improved Uncivilized Tactics",
  "Power Attack -> Uncivilized Tactics -> Improved Uncivilized Tactics -> Greater Uncivilized Tactics",
  "Power Attack -> Unfair Grip",
  "Prone Shooter",
  "Quillbreaker Defense",
  "Quivering Palm Versatility",
  "Rat Catcher",
  "Reap the Infirm",
  "Resisting Grappler",
  "Reverse-Feint",
  "River Raider",
  "Rubble Skirmisher",
  "Scorching Weapons",
  "Scorching Weapons -> Inner Flame",
  "Searing Distraction",
  "Serpent Lash",
  "Serpent Lash -> Greater Serpent Lash",
  "Shadow Strike",
  "Shared Quarry",
  "Shielded Stand",
  "Sisterhood Rampart",
  "Slashing Grace",
  "Sliding Dash",
  "Solo Maneuvers",
  "Solo Maneuvers -> Betraying Blow",
  "Spiked Destroyer",
  "Sprightly Armor",
  "Startoss Comet",
  "Startoss Comet -> Startoss Shower",
  "Steadfast Slayer",
  "Step Up",
  "Step Up -> Press to the Wall",
  "Step Up -> Skyseeker Thrash",
  "Step Up -> Skyseeker Thrash -> Skyseeker Impact",
  "Step Up -> Step Up and Strike",
  "Strike Back",
  "Subjective Slam",
  "Subjective Slam -> Greater Subjective Slam",
  "Swift Refuge",
  "Swift Refuge -> Swift Sprint",
  "Sympathetic Rage",
  "Thrill of the Hunt",
  "Throat Slicer",
  "Tracer Fire",
  "Traditional Weapons",
  "Twinned Feint",
  "Two-Weapon Fighting",
  "Two-Weapon Fighting -> Break Guard",
  "Two-Weapon Fighting -> Improved Two-Weapon Fighting",
  "Two-Weapon Fighting -> Improved Two-Weapon Fighting -> Greater Two-Weapon Fighting",
  "Two-Weapon Fighting -> Improved Two-Weapon Fighting -> Improved Two-Weapon Feint",
  "Two-Weapon Fighting -> Improved Two-Weapon Fighting -> Two-Weapon Rend",
  "Two-Weapon Fighting -> Shield Slam",
  "Two-Weapon Fighting -> Twin Fang Lunge",
  "Two-Weapon Fighting -> Two-Weapon Defense",
  "Two-Weapon Fighting -> Two-Weapon Feint",
  "Two-Weapon Fighting -> Two-Weapon Feint -> Improved Two-Weapon Feint",
  "Unbreakable",
  "Untwisting Iron Strength",
  "Untwisting Iron Strength -> Untwisting Iron Skin",
  "Unyielding Ferocity",
  "Vital Strike",
  "Vital Strike -> All-Consuming Swing",
  "Vital Strike -> Cloak and Dagger Tactics",
  "Vital Strike -> Devastating Strike",
  "Vital Strike -> Devastating Strike -> Improved Devastating Strike",
  "Vital Strike -> Diabolic Humiliation",
  "Vital Strike -> Diabolic Humiliation -> Diabolic Judgement",
  "Vital Strike -> Improved Vital Strike",
  "Vital Strike -> Improved Vital Strike -> Diabolic Judgement",
  "Vital Strike -> Improved Vital Strike -> Greater Vital Strike",
  "Vital Strike -> Soulwrecking Strike",
  "Vital Strike -> Staggering Blow",
  "Vital Strike -> Winter's Strike",
  "Voracious Blade",
  "Vulpine Pounce",
  "Wave Strike",
  "Weapon Adept",
  "Weapon Focus",
  "Weapon Focus -> Anatomical Savant",
  "Weapon Focus -> Aquadynamic Focus",
  "Weapon Focus -> Dazzling Display",
  "Weapon Focus -> Dazzling Display -> Brutal Coup de Grace",
  "Weapon Focus -> Dazzling Display -> Disheartening Display",
  "Weapon Focus -> Dazzling Display -> Gory Finish",
  "Weapon Focus -> Dazzling Display -> Motivating Display",
  "Weapon Focus -> Dazzling Display -> Shatter Defenses",
  "Weapon Focus -> Dazzling Display -> Shatter Defenses -> Deadly Stroke",
  "Weapon Focus -> Dazzling Display -> Violent Display",
  "Weapon Focus -> Greater Weapon Focus",
  "Weapon Focus -> Greater Weapon Focus -> Deadly Stroke",
  "Weapon Focus -> Penetrating Strike",
  "Weapon Focus -> Penetrating Strike -> Greater Penetrating Strike",
  "Weapon Focus -> Signature Strike Triumph",
  "Weapon Focus -> Weapon Specialization",
  "Weapon Focus -> Weapon Specialization -> Greater Weapon Specialization",
  "Weapon Focus -> Weapon Versatility",
  "Weapon Trick",
  "Weathered Warrior",
  "Wingclipper",
  "Witchbreaker"
]