{ // Weapon types

  var weapon_types =
  {
// NOTE : converting ammunition to weapons, some stats don't transfer (e.g., weight)
//  'Arrow'                       : { name : 'arrow'                     , weight :   2 , damage_SM : '1-6'  , damage_L : '1-6'  , notes : '' , types : [ 'bow' ]       , melee : false , hurled_or_missile : false , length : `` , space : `` , speed : , ac_mods_2_to_10 : [] },
//  'Quarrel (or Bolt), light'    : { name : 'light bolt'                , weight :   1 , damage_SM : '1-4'  , damage_L : '1-4'  , notes : '' , types : [ 'crossbow' ]  , melee : false , hurled_or_missile : false , length : `` , space : `` , speed : , ac_mods_2_to_10 : [] },
//  'Quarrel (or Bolt), heavy'    : { name : 'heavy bolt'                , weight :   2 , damage_SM : '2-5'  , damage_L : '2-7'  , notes : '' , types : [ 'crossbow' ]  , melee : false , hurled_or_missile : false , length : `` , space : `` , speed : , ac_mods_2_to_10 : [] },
//  'Sling bullet'                : { name : 'sling bullet'              , weight :   2 , damage_SM : '2-5'  , damage_L : '2-7'  , notes : '' , types : [ 'sling' ]     , melee : false , hurled_or_missile : false , length : `` , space : `` , speed : , ac_mods_2_to_10 : [] },
//  'Sling stone'                 : { name : 'sling stone'               , weight :   1 , damage_SM : '1-4'  , damage_L : '1-4'  , notes : '' , types : [ 'sling' ]     , melee : false , hurled_or_missile : false , length : `` , space : `` , speed : , ac_mods_2_to_10 : [] },
    'Bow, composite, long'        : { name : 'composite longbow'         , weight :   2 , damage_SM : '1-6'  , damage_L : '1-6'  , notes : '' , types : [ 'bow' ]       , melee : false , hurled_or_missile : true  }, // Bow, composite, long
    'Bow, composite, short'       : { name : 'composite shortbow'        , weight :   2 , damage_SM : '1-6'  , damage_L : '1-6'  , notes : '' , types : [ 'bow' ]       , melee : false , hurled_or_missile : true  }, // Bow, composite, short
    'Bow, long'                   : { name : 'longbow'                   , weight :   2 , damage_SM : '1-6'  , damage_L : '1-6'  , notes : '' , types : [ 'bow' ]       , melee : false , hurled_or_missile : true  }, // Bow, long
    'Bow, short'                  : { name : 'shortbow'                  , weight :   2 , damage_SM : '1-6'  , damage_L : '1-6'  , notes : '' , types : [ 'bow' ]       , melee : false , hurled_or_missile : true  }, // Bow, short
    // AC headers                                                                                                                                                                                                                                                                            2 ,  3 ,  4 ,  5 ,  6 ,  7 ,  8 ,  9 , 10
    'Axe, Battle'                 : { name : 'battle axe'                , weight :  75 , damage_SM : '1-8'  , damage_L : '1-8'  , notes : '' , types : [ 'axe' ]       , melee : true  , hurled_or_missile : false , length : `c. 4'`   , space : `4'`  , speed :  7 , ac_mods_2_to_10 : [ -3 , -2 , -1 , -1 ,  0 ,  0 , +1 , +1 , +2 ] }, // Axe, Battle
    'Axe, Hand or throwing'       : { name : 'hand axe'                  , weight :  50 , damage_SM : '1-6'  , damage_L : '1-4'  , notes : '' , types : [ 'axe' ]       , melee : true  , hurled_or_missile : true  , length : `c. 1.5'` , space : `1'`  , speed :  4 , ac_mods_2_to_10 : [ -3 , -2 , -2 , -1 ,  0 ,  0 , +1 , +1 , +1 ] }, // Axe, Hand or throwing
    'Bardiche'                    : { name : 'bardiche'                  , weight : 125 , damage_SM : '2-8'  , damage_L : '3-12' , notes : '' , types : [ 'polearm' ]   , melee : true  , hurled_or_missile : false , length : `c. 5'`   , space : `5'`  , speed :  9 , ac_mods_2_to_10 : [ -2 , -1 ,  0 ,  0 , +1 , +1 , +2 , +2 , +3 ] }, // Bardiche
    'Bec de corbin'               : { name : 'bec de corbin'             , weight : 100 , damage_SM : '1-8'  , damage_L : '1-6'  , notes : '' , types : [ 'polearm' ]   , melee : true  , hurled_or_missile : false , length : `c. 6'`   , space : `6'`  , speed :  9 , ac_mods_2_to_10 : [ +2 , +2 , +2 ,  0 ,  0 ,  0 ,  0 ,  0 , -1 ] }, // Bec de corbin
    'Bill-Guisarme'               : { name : 'bill-guisarme'             , weight : 150 , damage_SM : '2-8'  , damage_L : '1-10' , notes : '' , types : [ 'polearm' ]   , melee : true  , hurled_or_missile : false , length : `8'+`     , space : `2'`  , speed : 10 , ac_mods_2_to_10 : [  0 ,  0 ,  0 ,  0 ,  0 ,  0 , +1 ,  0 ,  0 ] }, // Bill-Guisarme
    'Bo Stick'                    : { name : 'bo stick'                  , weight :  15 , damage_SM : '1-6'  , damage_L : '1-3'  , notes : '' , types : [ 'bo stick' ]  , melee : true  , hurled_or_missile : false , length : `c. 5'`   , space : `3'`  , speed :  3 , ac_mods_2_to_10 : [ -9 , -7 , -5 , -3 , -1 ,  0 , +1 ,  0 , +3 ] }, // Bo Stick
    'Club'                        : { name : 'club'                      , weight :  30 , damage_SM : '1-6'  , damage_L : '1-3'  , notes : '' , types : [ 'club' ]      , melee : true  , hurled_or_missile : true  , length : `c. 3'`   , space : `2'`  , speed :  4 , ac_mods_2_to_10 : [ -5 , -4 , -3 , -2 , -1 , -1 ,  0 ,  0 , +1 ] }, // Club // averaged space required from 1'-3'
    'Dagger'                      : { name : 'dagger'                    , weight :  10 , damage_SM : '1-4'  , damage_L : '1-3'  , notes : '' , types : [ 'dagger' ]    , melee : true  , hurled_or_missile : true  , length : `c. 15"`  , space : `1'`  , speed :  2 , ac_mods_2_to_10 : [ -3 , -3 , -2 , -2 ,  0 ,  0 , +1 , +1 , +3 ] }, // Dagger
    'Dart'                        : { name : 'dart'                      , weight :   5 , damage_SM : '1-3'  , damage_L : '1-2'  , notes : '' , types : [ 'dart' ]      , melee : false , hurled_or_missile : true  }, // Dart
    'Fauchard'                    : { name : 'fauchard'                  , weight :  60 , damage_SM : '1-6'  , damage_L : '1-8'  , notes : '' , types : [ 'polearm' ]   , melee : true  , hurled_or_missile : false , length : `8'+`     , space : `2'`  , speed :  8 , ac_mods_2_to_10 : [ -2 , -2 , -1 , -1 ,  0 ,  0 ,  0 , -1 , -1 ] }, // Fauchard
    'Fauchard-Fork'               : { name : 'fauchard-fork'             , weight :  80 , damage_SM : '1-8'  , damage_L : '1-10' , notes : '' , types : [ 'polearm' ]   , melee : true  , hurled_or_missile : false , length : `8'`      , space : `2'`  , speed :  8 , ac_mods_2_to_10 : [ -1 , -1 , -1 ,  0 ,  0 ,  0 , +1 ,  0 , +1 ] }, // Fauchard-Fork
    'Fist or Open Hand'           : { name : 'unarmed'                   , weight :   0 , damage_SM : '0-0'  , damage_L : '0-0'  , notes : '' , types : [ 'unarmed' ]   , melee : true  , hurled_or_missile : false , length : `2'+`     , space : `-`   , speed :  1 , ac_mods_2_to_10 : [ -7 , -5 , -3 , -1 ,  0 ,  0 , +2 ,  0 , +4 ] }, // Fist or Open Hand
    'Flail, footman\'s'           : { name : 'footman\'s flail'          , weight : 150 , damage_SM : '2-7'  , damage_L : '2-8'  , notes : '' , types : [ 'flail' ]     , melee : true  , hurled_or_missile : false , length : `c. 4'`   , space : `6'`  , speed :  7 , ac_mods_2_to_10 : [ +2 , +2 , +1 , +2 , +1 , +1 , +1 , +1 , -1 ] }, // Flail, footman\'s
    'Flail, horseman\'s'          : { name : 'horseman\'s flail'         , weight :  35 , damage_SM : '2-5'  , damage_L : '2-5'  , notes : '' , types : [ 'flail' ]     , melee : true  , hurled_or_missile : false , length : `c. 2'`   , space : `4'`  , speed :  6 , ac_mods_2_to_10 : [  0 ,  0 ,  0 ,  0 ,  0 , +1 , +1 , +1 ,  0 ] }, // Flail, horseman\'s
    'Fork, Military'              : { name : 'military fork'             , weight :  75 , damage_SM : '1-8'  , damage_L : '2-8'  , notes : '' , types : [ 'polearm' ]   , melee : true  , hurled_or_missile : false , length : `7'+`     , space : `1`   , speed :  7 , ac_mods_2_to_10 : [ -2 , -2 , -1 ,  0 ,  0 , +1 , +1 ,  0 , +1 ] }, // Fork, Military
    'Glaive'                      : { name : 'glaive'                    , weight :  75 , damage_SM : '1-6'  , damage_L : '1-10' , notes : '' , types : [ 'polearm' ]   , melee : true  , hurled_or_missile : false , length : `8'+`     , space : `1'`  , speed :  8 , ac_mods_2_to_10 : [ -1 , -1 ,  0 ,  0 ,  0 ,  0 ,  0 ,  0 ,  0 ] }, // Glaive
    'Glaive-Guisarme'             : { name : 'glaive-guisarme'           , weight : 100 , damage_SM : '2-8'  , damage_L : '2-12' , notes : '' , types : [ 'polearm' ]   , melee : true  , hurled_or_missile : false , length : `8'+`     , space : `1'`  , speed :  9 , ac_mods_2_to_10 : [ -1 , -1 ,  0 ,  0 ,  0 ,  0 ,  0 ,  0 ,  0 ] }, // Glaive-Guisarme
    'Guisarme'                    : { name : 'guisarme'                  , weight :  80 , damage_SM : '2-8'  , damage_L : '1-8'  , notes : '' , types : [ 'polearm' ]   , melee : true  , hurled_or_missile : false , length : `6'+`     , space : `2'`  , speed :  8 , ac_mods_2_to_10 : [ -2 , -2 , -1 , -1 ,  0 ,  0 ,  0 , -1 , -1 ] }, // Guisarme
    'Guisarme-Voulge'             : { name : 'guisarme-voulge'           , weight : 150 , damage_SM : '2-8'  , damage_L : '2-8'  , notes : '' , types : [ 'polearm' ]   , melee : true  , hurled_or_missile : false , length : `7'+`     , space : `2'`  , speed : 10 , ac_mods_2_to_10 : [ -1 , -1 ,  0 , +1 , +1 , +1 ,  0 ,  0 ,  0 ] }, // Guisarme-Voulge
    'Halberd'                     : { name : 'halberd'                   , weight : 175 , damage_SM : '1-10' , damage_L : '2-12' , notes : '' , types : [ 'polearm' ]   , melee : true  , hurled_or_missile : false , length : `5'+`     , space : `5'`  , speed :  9 , ac_mods_2_to_10 : [ +1 , +1 , +1 , +2 , +2 , +2 , +1 , +1 ,  0 ] }, // Halberd
    'Hammer, Lucern'              : { name : 'lucern hammer'             , weight : 150 , damage_SM : '2-8'  , damage_L : '1-6'  , notes : '' , types : [ 'hammer' ]    , melee : true  , hurled_or_missile : false , length : `5'+`     , space : `5'`  , speed :  9 , ac_mods_2_to_10 : [ +1 , +1 , +2 , +2 , +2 , +1 , +1 ,  0 ,  0 ] }, // Hammer, Lucern
    'Hammer'                      : { name : 'hammer'                    , weight :  50 , damage_SM : '2-5'  , damage_L : '1-4'  , notes : '' , types : [ 'hammer' ]    , melee : true  , hurled_or_missile : true  , length : `c. 1.5'` , space : `2'`  , speed :  4 , ac_mods_2_to_10 : [  0 , +1 ,  0 , +1 ,  0 ,  0 ,  0 ,  0 ,  0 ] }, // Hammer
    'Javelin'                     : { name : 'javelin'                   , weight :  20 , damage_SM : '1-6'  , damage_L : '1-6'  , notes : '' , types : [ 'javelin' ]   , melee : false , hurled_or_missile : true  }, // Javelin
    'Jo Stick'                    : { name : 'jo stick'                  , weight :  40 , damage_SM : '1-6'  , damage_L : '1-4'  , notes : '' , types : [ 'jo stick' ]  , melee : true  , hurled_or_missile : false , length : `c. 3'`   , space : `2'`  , speed :  2 , ac_mods_2_to_10 : [ -8 , -6 , -4 , -2 , -1 ,  0 , +1 ,  0 , +2 ] }, // Jo Stick
    'Lance (light horse)'         : { name : 'lance (light horse)'       , weight :  50 , damage_SM : '1-6'  , damage_L : '1-8'  , notes : '' , types : [ 'polearm' ]   , melee : true  , hurled_or_missile : false , length : `10'`     , space : `1'`  , speed :  7 , ac_mods_2_to_10 : [ -2 , -2 , -1 ,  0 ,  0 ,  0 ,  0 ,  0 ,  0 ] }, // Lance (light horse)
    'Lance (medium horse)'        : { name : 'lance (medium horse)'      , weight : 100 , damage_SM : '2-7'  , damage_L : '2-12' , notes : '' , types : [ 'polearm' ]   , melee : true  , hurled_or_missile : false , length : `12'`     , space : `1'`  , speed :  6 , ac_mods_2_to_10 : [  0 , +1 , +1 , +1 , +1 ,  0 ,  0 ,  0 ,  0 ] }, // Lance (medium horse)
    'Lance (heavy horse)'         : { name : 'lance (heavy horse)'       , weight : 150 , damage_SM : '3-9'  , damage_L : '3-18' , notes : '' , types : [ 'polearm' ]   , melee : true  , hurled_or_missile : false , length : `c. 14'`  , space : `1'`  , speed :  8 , ac_mods_2_to_10 : [ +3 , +3 , +2 , +2 , +2 , +1 , +1 ,  0 ,  0 ] }, // Lance (heavy horse)
    'Mace, footman\'s'            : { name : 'footman\'s mace'           , weight : 100 , damage_SM : '2-7'  , damage_L : '1-6'  , notes : '' , types : [ 'mace' ]      , melee : true  , hurled_or_missile : false , length : `c. 2.5'` , space : `4'`  , speed :  7 , ac_mods_2_to_10 : [ +1 , +1 ,  0 ,  0 ,  0 ,  0 ,  0 , +1 , -1 ] }, // Mace, footman\'s
    'Mace, horseman\'s'           : { name : 'horseman\'s mace'          , weight :  50 , damage_SM : '1-6'  , damage_L : '1-4'  , notes : '' , types : [ 'mace' ]      , melee : true  , hurled_or_missile : false , length : `c. 1.5'` , space : `2'`  , speed :  6 , ac_mods_2_to_10 : [ +1 , +1 ,  0 ,  0 ,  0 ,  0 ,  0 ,  0 ,  0 ] }, // Mace, horseman\'s
    'Morning Star'                : { name : 'morning star'              , weight : 125 , damage_SM : '2-8'  , damage_L : '2-7'  , notes : '' , types : [ 'flail' ]     , melee : true  , hurled_or_missile : false , length : `c. 4'`   , space : `5'`  , speed :  7 , ac_mods_2_to_10 : [  0 , +1 , +1 , +1 , +1 , +1 , +1 , +2 , +2 ] }, // Morning Star
    'Partisan'                    : { name : 'partisan'                  , weight :  80 , damage_SM : '1-6'  , damage_L : '2-7'  , notes : '' , types : [ 'polearm' ]   , melee : true  , hurled_or_missile : false , length : `7'+`     , space : `3'`  , speed :  9 , ac_mods_2_to_10 : [  0 ,  0 ,  0 ,  0 ,  0 ,  0 ,  0 ,  0 ,  0 ] }, // Partisan
    'Pick, Military, footman\'s'  : { name : 'footman\'s military pick'  , weight :  60 , damage_SM : '2-7'  , damage_L : '2-8'  , notes : '' , types : [ 'polearm' ]   , melee : true  , hurled_or_missile : false , length : `c. 4'`   , space : `4'`  , speed :  7 , ac_mods_2_to_10 : [ +2 , +2 , +1 , +1 ,  0 , -1 , -1 , -1 , -2 ] }, // Pick, Military, footman\'s
    'Pick, Military, horseman\'s' : { name : 'horseman\'s military pick' , weight :  40 , damage_SM : '2-5'  , damage_L : '1-4'  , notes : '' , types : [ 'polearm' ]   , melee : true  , hurled_or_missile : false , length : `c. 2'`   , space : `2'`  , speed :  5 , ac_mods_2_to_10 : [ +1 , +1 , +1 , +1 ,  0 ,  0 , -1 , -1 , -1 ] }, // Pick, Military, horseman\'s
    'Pike, Awl'                   : { name : 'awl pike'                  , weight :  80 , damage_SM : '1-6'  , damage_L : '1-12' , notes : '' , types : [ 'polearm' ]   , melee : true  , hurled_or_missile : false , length : `18'+`    , space : `1'`  , speed : 13 , ac_mods_2_to_10 : [ -1 ,  0 ,  0 ,  0 ,  0 ,  0 ,  0 , -1 , -2 ] }, // Pike, Awl
    'Crossbow, light'             : { name : 'light crossbow'            , weight :   1 , damage_SM : '1-4'  , damage_L : '1-4'  , notes : '' , types : [ 'crossbow' ]  , melee : false , hurled_or_missile : true  }, // Crossbow, light
    'Crossbow, heavy'             : { name : 'heavy crossbow'            , weight :   2 , damage_SM : '2-5'  , damage_L : '2-7'  , notes : '' , types : [ 'crossbow' ]  , melee : false , hurled_or_missile : true  }, // Crossbow, heavy
    'Ranseur'                     : { name : 'ranseur'                   , weight :  50 , damage_SM : '2-8'  , damage_L : '2-8'  , notes : '' , types : [ 'polearm' ]   , melee : true  , hurled_or_missile : false , length : `8'+`     , space : `1'`  , speed :  8 , ac_mods_2_to_10 : [ -2 , -1 , -1 ,  0 ,  0 ,  0 ,  0 ,  0 , +1 ] }, // Ranseur
    'Scimitar'                    : { name : 'scimitar'                  , weight :  40 , damage_SM : '1-8'  , damage_L : '1-8'  , notes : '' , types : [ 'sword' ]     , melee : true  , hurled_or_missile : false , length : `c. 3'`   , space : `2'`  , speed :  4 , ac_mods_2_to_10 : [ -3 , -2 , -2 , -1 ,  0 ,  0 , +1 , +1 , +3 ] }, // Scimitar
    'Sling (bullet)'              : { name : 'sling (bullet)'            , weight :   2 , damage_SM : '2-5'  , damage_L : '2-7'  , notes : '' , types : [ 'sling' ]     , melee : false , hurled_or_missile : true  }, // Sling (bullet
    'Sling (stone)'               : { name : 'sling (stone)'             , weight :   1 , damage_SM : '1-4'  , damage_L : '1-4'  , notes : '' , types : [ 'sling' ]     , melee : false , hurled_or_missile : true  }, // Sling (stone
    'Spear'                       : { name : 'spear'                     , weight :  50 , damage_SM : '1-6'  , damage_L : '1-8'  , notes : '' , types : [ 'spear' ]     , melee : true  , hurled_or_missile : true  , length : `9'+`     , space : `1'`  , speed :  7 , ac_mods_2_to_10 : [ -2 , -1 , -1 , -1 ,  0 ,  0 ,  0 ,  0 ,  0 ] }, // Spear // averaged weight from 40-60, speed from 6-8, length from 5'-13'+
    'Spetum'                      : { name : 'spetum'                    , weight :  50 , damage_SM : '2-7'  , damage_L : '2-12' , notes : '' , types : [ 'polearm' ]   , melee : true  , hurled_or_missile : false , length : `8'+`     , space : `1'`  , speed :  8 , ac_mods_2_to_10 : [ -2 , -1 ,  0 ,  0 ,  0 ,  0 ,  0 , +1 , +2 ] }, // Spetum
    'Staff, Quarter'              : { name : 'quarterstaff'              , weight :  50 , damage_SM : '1-6'  , damage_L : '1-6'  , notes : '' , types : [ 'staff' ]     , melee : true  , hurled_or_missile : false , length : `7'`      , space : `3'`  , speed :  4 , ac_mods_2_to_10 : [ -7 , -5 , -3 , -1 ,  0 ,  0 , +1 , +1 , +1 ] }, // Staff, Quarter // averaged length from 6'-8'
    'Sword, Bastard'              : { name : 'bastard sword'             , weight : 100 , damage_SM : '2-8'  , damage_L : '2-16' , notes : '' , types : [ 'sword' ]     , melee : true  , hurled_or_missile : false , length : `c. 4.5'` , space : `4'+` , speed :  6 , ac_mods_2_to_10 : [  0 ,  0 , +1 , +1 , +1 , +1 , +1 , +1 ,  0 ] }, // Sword, Bastard
    'Sword, Broad'                : { name : 'broadsword'                , weight :  75 , damage_SM : '2-8'  , damage_L : '2-7'  , notes : '' , types : [ 'sword' ]     , melee : true  , hurled_or_missile : false , length : `c. 3.5'` , space : `4'`  , speed :  5 , ac_mods_2_to_10 : [ -3 , -2 , -1 ,  0 ,  0 , +1 , +1 , +1 , +2 ] }, // Sword, Broad
    'Sword, Long'                 : { name : 'long sword'                , weight :  60 , damage_SM : '1-8'  , damage_L : '1-12' , notes : '' , types : [ 'sword' ]     , melee : true  , hurled_or_missile : false , length : `c. 3.5'` , space : `3'`  , speed :  5 , ac_mods_2_to_10 : [ -2 , -1 ,  0 ,  0 ,  0 ,  0 ,  0 ,  0 , +2 ] }, // Sword, Long
    'Sword, Short'                : { name : 'short sword'               , weight :  35 , damage_SM : '1-6'  , damage_L : '1-8'  , notes : '' , types : [ 'sword' ]     , melee : true  , hurled_or_missile : false , length : `c. 2'`   , space : `1'`  , speed :  3 , ac_mods_2_to_10 : [ -3 , -2 , -1 ,  0 ,  0 ,  0 , +1 ,  0 , +2 ] }, // Sword, Short
    'Sword, Two-handed'           : { name : 'two-handed sword'          , weight : 250 , damage_SM : '1-10' , damage_L : '3-18' , notes : '' , types : [ 'sword' ]     , melee : true  , hurled_or_missile : false , length : `c. 6'`   , space : `6'`  , speed : 10 , ac_mods_2_to_10 : [ +2 , +2 , +2 , +2 , +3 , +3 , +3 , +1 ,  0 ] }, // Sword, Two-handed
    'Trident'                     : { name : 'trident'                   , weight :  50 , damage_SM : '2-7'  , damage_L : '3-12' , notes : '' , types : [ 'polearm' ]   , melee : true  , hurled_or_missile : false , length : `6'`      , space : `1'`  , speed :  7 , ac_mods_2_to_10 : [ -3 , -2 , -1 , -1 ,  0 ,  0 , +1 ,  0 , +1 ] }, // Trident // averaged speed from 6-8, length from 4'-8'
    'Voulge'                      : { name : 'voulge'                    , weight : 125 , damage_SM : '2-8'  , damage_L : '2-8'  , notes : '' , types : [ 'polearm' ]   , melee : true  , hurled_or_missile : false , length : `8'+`     , space : `2'`  , speed : 10 , ac_mods_2_to_10 : [ -1 , -1 ,  0 , +1 , +1 , +1 ,  0 ,  0 ,  0 ] } // Voulge
  };
  
}